#! /bin/sh

if [ $(pgrep -cx panel) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc control --subscribe > "$PANEL_FIFO" &
xtitle -sf 'T%s' > "$PANEL_FIFO" &
panel_volume > "$PANEL_FIFO" &
panel_battery > "$PANEL_FIFO" &
panel_wifi > "$PANEL_FIFO" &
clock -sf 'S%I:%M %p' > "$PANEL_FIFO" &

cat "$PANEL_FIFO" | ~/.config/bspwm/panel/panel_bar | bar &

wait
