#! /bin/sh

# desktops
bspc monitor -d term web media text docs

# visual options
bspc config border_width            1
bspc config window_gap              20
bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   false
bspc config top_padding             15
bspc config right_padding           0
bspc config bottom_padding          0
bspc config left_padding            0
bspc config normal_border_color     "#000000"
bspc config active_border_color     "#0000FF"
#bspc config focused_border_color   "#CAB775"
bspc config focused_border_color    "#F0EE9C"
bspc config presel_border_color     "#F7F9FF"
bspc config urgent_border_color     "#00FF00"
bspc config -d web border_width     0

# application rules
bspc rule -a Chromium desktop=^2 fullscreen=false
bspc rule -a Firefox desktop=^2 fullscreen=false

# launch panel
/home/dion/.config/bspwm/panel/panel &
